name: Sync Repositories

on:
  schedule:
    - cron: '55 12* * *'  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sync with Bitbucket
      run: |
        git remote add bitbucket https://fmyersdev@bitbucket.org/desarrollo-lawebes/lawebnew.git
        git pull --no-edit bitbucket master
        git push origin master
